---
name: CI

on: [push]

jobs:
  Server-Lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cd server && make lint

  Server-Unit_Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cd server && make test
